container:
  image: YOUR_IMAGE_URI
  minReplicasCount: 2
  maxReplicasCount: 4
  port: 3000
  name: node-js-application

serviceAccount:
  roleARN: YOUR_ROLE_ARN
  name: app

secretName: my-secret-01

secretsManagerSecretName: prod/app/variables

spaceId:
  alias: space_id
  secretKey: CONTENTFUL_SPACE_ID
  secretObjectKey: space_id_01

deliveryToken:
  alias: delivery_token
  secretKey: CONTENTFUL_DELIVERY_TOKEN
  secretObjectKey: delivery_token_01

previewToken:
  alias: preview_token
  secretKey: CONTENTFUL_PREVIEW_TOKEN
  secretObjectKey: preview_token_01

storageClass:
  name: efs-sc
  directoryPerms: 700

pvc:
  name: efs-claim
  storage: 5Gi

pv:
  name: persistent-storage
  mountPath: /data

secretsVolume:
  name: secrets-store-inline
  mountPath: /mnt/secrets

efsId: YOUR_EFS_ID

podSelectorLabel: app

svc:
  type: ClusterIP
  port: 80

hpa:
  cpuAverageUtilization: 80
  memoryAverageUtilization: 80

ingress:
  targetType: ip
  sslCertificateARN: YOUR_SSL_CERTIFICATE_ARN
  scheme: internet-facing 

livenessProbe:
  initialDelaySeconds: 5
  periodSeconds: 5

readinessProbe:
  initialDelaySeconds: 5
  periodSeconds: 5
