---
# tasks file for deploy_application

- name: Deploy application using helm
  shell:
   kubectl apply -f ~/ansible/namespace/namespace.yaml &&  helm install {{ helm_release_name }} ~/ansible/Node_App_Chart/ -n {{ helm_release_name }}
  register: deploy_results

- debug:
   var: deploy_results.stdout_lines

