---
# tasks file for upgrade_release

- name: Get the latest image tag from ECR
  shell:
   aws ecr describe-images --repository-name node-app --region us-east-1 --query 'sort_by(imageDetails,& imagePushedAt)[-1].imageTags[0]' --output text
  register: latest_ecr_image_tag


- name: Upgrade existing helm release
  shell:
   helm upgrade {{ helm_release_name }} ~/ansible/Node_App_Chart/ --set container.image=999360891534.dkr.ecr.us-east-1.amazonaws.com/node-app:{{ latest_ecr_image_tag.stdout }}
  register: upgrade_results


- debug:
   var: upgrade_results.stdout_lines

