---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: {{ .Release.Name }}
  name: {{ .Values.pvc.name }}
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: {{ .Values.storageClass.name }}
  resources:
    requests:
      storage: {{ .Values.pvc.storage }}