apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ .Release.Name }}-deployment-spc-k8s-secrets
  namespace: {{ .Release.Name }}
spec:
  provider: aws
  parameters: 
    objects: |
      - objectName: "{{ .Values.secretsManagerSecretName }}"
        objectType: "secretsmanager"
        jmesPath:
          - path: {{ .Values.spaceId.secretKey }}
            objectAlias: {{ .Values.spaceId.alias }}
          - path: {{ .Values.deliveryToken.secretKey }}
            objectAlias: {{ .Values.deliveryToken.alias }}
          - path: {{ .Values.previewToken.secretKey }}
            objectAlias: {{ .Values.previewToken.alias }}
  secretObjects:
    - secretName: {{ .Values.secretName }}
      type: Opaque
      data:
        - objectName: {{ .Values.spaceId.alias }}
          key: {{ .Values.spaceId.secretObjectKey }}
        - objectName: {{ .Values.deliveryToken.alias }}
          key: {{ .Values.deliveryToken.secretObjectKey }}
        - objectName: {{ .Values.previewToken.alias }}
          key: {{ .Values.previewToken.secretObjectKey }}

